### ISSUE TITLE
Error on gulp serve

### ISSUE THREAD

**Issue by therealcljohn** [reyesoft/ts-angular-jsonapi#8]
Hi,

I'm getting an error when using `gulp serve` to run the demo:

```
[floh1111@flohlap ts-angular-jsonapi]$ gulp serve
module.js:442
    throw err;
    ^

Error: Cannot find module '/usr/lib/node_modules/gulp/node_modules/v8flags/cache/5.0.71.52.flags.json'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/gulp/bin/gulp.js:25:22)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

Using `npm start` instead of `gulp serve` works fine for me so maybe you can just update the README. Versions used:

```
[floh1111@flohlap ~]$ npm --version
3.10.5
[floh1111@flohlap ~]$ node --version
v6.3.0
```

**Comment by pablorsk** [comment]
try with this, please:

```
npm install -g gulp
```

Apparently you have not installed correctly `gulp`. Check with something like this:

```
$ gulp -v
[12:12:30] CLI version 3.9.1
[12:12:30] Local version 3.9.1
```

**Comment by therealcljohn** [comment]
Hi pablorsk,

thank you for helping me out on this issue. I'm actually quite new to Angular and all the stuff around. Reinstalling gulp did the trick!

Best whishes
